Use longitude-one/wkt-parser, remove php 7.4 & 8.0 support (#37)
* Allows axi version

* Use longitude-one/wkt-parser

* Use longitude-one/wkt-parser

* Migrate tests from annotations to attributes, fixes for doctrine/annotation 2

* Remove php7.4 & 8.0 support

* Fix codeclimate error ?

Generating code coverage report in Clover XML format ... done [00:00.232]
Script phpunit --configuration phpunit.mysql5.7.xml handling the test event returned with error code 1
Error: The process '/usr/local/bin/composer' failed with exit code 1
(node:4044) UnhandledPromiseRejectionWarning: Error: The process '/usr/local/bin/composer' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/exec/lib/toolrunner.js:574:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/exec/lib/toolrunner.js:557:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/exec/lib/toolrunner.js:451:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
(node:4044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: 🚨 Coverage run failed!

* Test: do not compare float strictly (see https://www.php.net/manual/en/language.types.float.php "Floating point precision") so tests will succeed on different linux / windows platforms

* Tests: fix 2 more tests

* Allows tests to be executed by GitHub Actions in forked repositories

* Apply php-cs-fixer command

---------

Co-authored-by: Alexis Urien <alexis@smiile.com>